### ISSUE TITLE
[FEATURE REQUEST] daily data

### ISSUE THREAD

**Issue by paulius2k** [Brunas/meteo_lt#15]
Hi,

would it be possible to add daily data as well? Like met.no e.g.:
<img src="https://github.com/user-attachments/assets/a92ea254-730b-4e96-9c5b-0b706b657b38" width=50%>

so that daily weather cards show nicely:
<img src="https://github.com/user-attachments/assets/5a4d0876-f056-450e-91be-a27635e13ada" width=50%>

Ačiū.

**Comment by Brunas** [comment]
@paulius2k unfortunately this can't be implemented since api.meteo.lt doesn't provide daily forecast - only hourly. More info can be found in [api.meteo.lt](https://api.meteo.lt). For sure, if that was available, daily would have been already implemented. I hope that will change and we might come back to implementing daily forecast.
